### ISSUE TITLE
Zip code to ip address mapping

### ISSUE THREAD

**Issue by dev2021-ctrl** [sapics/ip-location-db#12]
Can you please let me know how to get any 2 ip addresses for specific US zip code
Example I want to get the ip addresss for 99901 .now within this zip code , we can have many ips .
I just need 2-3 ips.
Similarly for other us zip codes.

Can you suggest any API or may be some data that I can download.

 A bit urgent

**Comment by sapics** [comment]
`geolite2-city` data includes postcode.

**Comment by dev2021-ctrl** [comment]
yes but it does not have ip address mapping .
It only has network address and not any real ip address that can be used

**Comment by sapics** [comment]
I understand what you want. Yes, we have no mapping data.

GeoLite2 is provided by [MaxMind](https://www.maxmind.com), it would be better to contact them, because we just redistribute their database.
There is also a commercial version [GeoIp2](https://www.maxmind.com/en/geoip2-databases) which has better accuracy, it might help you.

**Comment by dev2021-ctrl** [comment]
pls let me know where to get the mmdb binary file for the corresposnign
GeoLite2-City-Blocks-IPv4.csv file.
I can only find the csv file but will need a binary too.

**Comment by sapics** [comment]
We create only csv files.
