### ISSUE TITLE
all links for Type=City are dead, please fix

### ISSUE THREAD

**Issue by SK-StYleZ** [sapics/ip-location-db#25]
getting 404

**Comment by sapics** [comment]
Thanks @SK-StYleZ for reporting dead links!
I guess that the github system for large files have changed.
(ex: https://github.com/sapics/ip-location-db/blob/main/geolite2-city-7z/geolite2-city-ipv4-num.csv.7z)

I fix links in top README.md file, and the other README files in each directory would be fixed in a few days.

**Comment by SK-StYleZ** [comment]
Thank You @sapics for the fast fix <3
