### ISSUE TITLE
Which db to trust ?! They all give different answers

### ISSUE THREAD

**Issue by imTHAI** [sapics/ip-location-db#38]
Hello,

I was checking an ip (37.9.43.152)

DB-IP says it's from USA : `37.9.40.0,37.9.43.255,US`
IPtoASN says it's from GB: `37.9.40.0,37.9.47.255,GB`

And max-mind says its from Russia: (from their website: `Russia (RU), Europe	37.9.40.0/21`

And finally, if I check on the RIPE (ripe.net) it says it's from France:
<img width="462" alt="image" src="https://github.com/user-attachments/assets/e9d12320-ee4d-4cd7-8618-87f22ba9d562">

😱

Why don't they agree? If it's a question of updating, it would be interesting to know the history of this subnet (if it's been allocated from country to country) so we'd know which db is updated the least quickly.

Which db do you recommend ?

Thank you

**Comment by sapics** [comment]
Hi,

It is an interesting ip with many differences!
We provide multiple database because there are differences ;)

From asn-country database, it is "RU".
From geo-asn-country database, it is "FR".
It means that a geofeed provider says the ip is "FR".

The geofeed url is https://geofeed.pinspb.ru/geofeed.csv which has Last-Modified header "Tue, 15 Oct 2024 04:04:38 GMT".
It means that the geofeed provider keeps updating the database.
The top level domain of geofeed url is ".ru", thus the provider might be "RU" company.

The geofeed csv says it is "RU" or "FR", but I consider that "37.9.43.0/24,FR" is more accurate than "37.9.40.0/21,RU".

```csv
37.9.40.0/24,RU
37.9.40.0/21,RU
37.9.41.0/24,FR
37.9.42.0/24,FR
37.9.43.0/24,FR
```

Therefore, I guess that the ip address would be located at "FR", as my conclusion.

**Comment by sapics** [comment]
It is difficult to make a recommendation for accuracy, but since the difference between "geolite2-country" and the other database is only a few percent as [README](https://github.com/sapics/ip-location-db?tab=readme-ov-file#accuracy-of-database), we recommend to use "geo-asn-country" or "geo-whois-asn-country" or "geolite2-geo-whois-asn-country" or "dbip-geo-whois-asn-country".

We especially recommend "geo-asn-country" and "geo-whois-asn-country" because they are license-free.

**Comment by imTHAI** [comment]
> The geofeed csv says it is "RU" or "FR", but I consider that "37.9.43.0/24,FR" is more accurate than "37.9.40.0/21,RU".
Such overlap should not even happen. For me all these db's should contain no overlap, to be considered even remotely serious.

But let me get this straight. Where do all these companies get their information from? 
Shouldn't they be getting it from the RIRs (ARIN, RIPE, etc.)? The RIRs MUST have up-to-date information, since they're the ones who allocate the ip blocks, right?

That's why, in the case of ip 37, I think it's a FR since the RIPE says it's a FR.

**Comment by sapics** [comment]
> Such overlap should not even happen. For me all these db's should contain no overlap, to be considered even remotely serious.

Unfortunately, many databases contain such overlapping data.

> Where do all these companies get their information from?

I have no information about that, I guess that it would be created by themselves for free.
The format is called "A Format for Self-Published IP Geolocation Feeds", as [RFC 8805](https://datatracker.ietf.org/doc/html/rfc8805).
Not many providers offer the geofeed, so we are grateful that they offer it free of charge.
